services:
  webapp:
    image: sandersonck/webapp
    container_name: webapp
    depends_on:
      database:
        condition: service_healthy
    ports:
      - 3000:3000
    environment:
      MYSQL_URL: mysql://sander:sander@database:3306/animals
      # mysql://<USER>:<PASSWORD>@<HOST>:<PORT>/<DATABASE> 
    volumes:
      - ./database:/app/database

  database:
    image: mysql:latest
    container_name: database
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: sander
      MYSQL_PASSWORD: sander
      MYSQL_DATABASE: animals
    ports:
      - 33060:3306
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
      start_period: 3s
      interval: 1s
      timeout: 1s
      retries: 55
    volumes:
      - database2:/app/database2

  tests:
    image: sandersonck/webapp
    container_name: tests
    environment: 
      API_URL: http://webapp:3000
    depends_on:
      - webapp
    command: yarn test

volumes:
  database:
  database2:
    name: "my-app-data"
    
